server:
  port: 8080

logging:
  level: INFO
    com:
      github:
        shaart:
          jenkins2discord:
            notification: INFO

jenkins2discord:
  request:
    read-timeout: 5000
    connect-timeout: 5000
  jenkins:
    address: http://localhost:8080
  discord:
    webhook:
      url:
    message:
      username:
      avatar-url:
      prefix: "[JENKINS]"